os: Visual Studio 2015

platform:
  - Win32

before_build:
  - cmd: git clean -ffxd

build_script:
  - cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - cmd: nmake -f Bootstrap.mak MSDEV=vs2015 windows

test_script:
  - cmd: bin\release\premake5 test
